# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# Caution: this setting can cause issues with multiline prompts (zsh 5.7.1 and newer seem to work)
# See https://github.com/ohmyzsh/ohmyzsh/issues/5765
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source "$ZSH"/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

## SECRETS
if [ -f ~/.secretsrc ]; then
  source ~/.secretsrc
fi

## ---
## GIT
## --
alias gms="git fetch; git checkout master; git status"
alias gbd="git branch --merged | grep -v \* | xargs git branch -d"

## VS CODE

if [ "$(uname -s)" = "Darwin" ]; then
  export PATH="$PATH":"/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
fi

## GOOGLE CLOUD SDK

export PATH="$PATH":~/.google-cloud-sdk/bin

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/cera/.google-cloud-sdk/path.zsh.inc' ]; then . '/Users/cera/.google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/cera/.google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/cera/.google-cloud-sdk/completion.zsh.inc'; fi

## KUBERNETES
alias k="kubectl"

## RUBY
alias be="bundle exec"

## RUST
if [ -f "$HOME"/.cargo/env ]; then
  source "$HOME"/.cargo/env
fi

## NPM
if [ -d ~/.npm-packages/bin ]; then
  export PATH="$PATH":~/.npm-packages/bin
fi

## ASDF
if [ -d "$HOME"/.asdf ]; then
  source "$HOME"/.asdf/asdf.sh
  source "$HOME"/.asdf/completions/asdf.bash
fi

## GREENSYNC

if [ -d "$HOME"/src/gs ]; then
  export PROJECTS="$HOME/src/gs"
fi

if [ -d "$PROJECTS"/platform-tools/kubernetes-tools ]; then
  export PATH="$PATH":"$PROJECTS"/platform-tools/kubernetes-tools
fi

work_with_dex() {
  source ~/.config/gs/dex-secrets.sh
  source "$PROJECTS"/dex-core/scripts/shell-utils/jwt.sh
  source "$PROJECTS"/dex-core/scripts/shell-utils/dex-environments-vars.sh
}

with-deploytools() {
  local google_creds_path
  google_creds_path=${GOOGLE_APPLICATION_CREDENTIALS:-$(gcloud info --format="value(config.paths.global_config_dir)")/application_default_credentials.json}

  docker run -it --rm \
    -v "$google_creds_path":/google-creds:ro \
    -e GOOGLE_APPLICATION_CREDENTIALS=/google-creds \
    --mount="type=bind,src=${PWD},dst=/work" \
    -w /work \
    asia.gcr.io/greensync-container-registry/deploytools:2020.10 \
    "${@-bash}"
}
