#!/bin/bash

set -Eeuo pipefail

cd "$(dirname "$0")"

here="$(pwd)"

while read source dest; do
  echo "$source -> $dest"
  # eval is required here to handle expansions e.g. ~/
  dest="$(eval echo $dest)"
  full_source=$here"/dotfiles/"$source
  if ! test -L "$dest"; then
    ln -s "$full_source" "$dest"
  elif [ "$(readlink $dest)" != "$full_source" ]; then
    echo "$dest exists but is not a link to $full_source" >&2
    exit 1
  fi
done < manifest

## VIM

vundleDir=~/.vim/bundle/Vundle.vim
test -d "$vundleDir" || git clone https://github.com/VundleVim/Vundle.vim.git "$vundleDir"
vim +PluginInstall +qall

## GOOGLE CLOUD SDK

cloudsdk_version=332.0.0

if ! [ -d ~/.google-cloud-sdk ]; then
  (
    cd /tmp
    curl -sO "https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${cloudsdk_version}-linux-x86_64.tar.gz"
    tar xzf "google-cloud-sdk-${cloudsdk_version}-linux-x86_64.tar.gz"
    mv google-cloud-sdk ~/.google-cloud-sdk
    ~/.google-cloud-sdk/bin/gcloud components install -q kubectl beta
    rm "/tmp/google-cloud-sdk-${cloudsdk_version}-linux-x86_64.tar.gz"
  )
fi

## MACOS

### BREW

if [ "$(uname -s)" == "Darwin" ]; then

if ! which brew >/dev/null; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/ollie/.zprofile
  eval "$(/opt/homebrew/bin/brew shellenv)"
  brew update
fi

### JQ
if ! which jq >/dev/null; then
  brew install jq
fi

### wget
if ! which wget >/dev/null; then
  brew install wget
fi

### kubernetes
if ! which kubectx >/dev/null; then
  brew install kubectx
fi

if ! which kustomize >/dev/null; then
  brew install kustomize
fi

fi
