#!/bin/bash

set -Eeuo pipefail

cd "$(dirname "$0")"

here="$(pwd)"

while read source dest; do
  echo "$source -> $dest"
  # eval is required here to handle expansions e.g. ~/
  dest=$(eval echo $dest)
  test -L "$dest" || ln -s "$here"/dotfiles/"$source" "$dest"
done < manifest

## VIM

vundleDir=~/.vim/bundle/Vundle.vim
test -d "$vundleDir" || git clone https://github.com/VundleVim/Vundle.vim.git "$vundleDir"
vim +PluginInstall +qall

## MACOS: BREW

if [ "$(uname -s)" == "Darwin" ] && ! which brew >/dev/null; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/ollie/.zprofile
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi
